spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hls
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        hibernate.ddl-auto: update

security:
    jwt:
        token:
            secret-key: mysecretasdfjfds773463463463463463463463463463hdfh
            expiration: 600000
        refreshToken:
            expiration: 1200000


logging:
    level:
        org:
            springframework: DEBUG
            hibernate:
                SQL: DEBUG
        com:
            tripod:
                homeloansystem: DEBUG

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: "*"

